export const CATEGORIES = [
    "Featured",
    "Documenting",
    "Experiment",
    "Debate",
    "Drama",
    "Geopolitics",
    "History",
    "Philosophy",
    "Psychology",
    "Science",
    "Technology",
    "Travel",
    "News",
    "Religion",
    "Anime",
    "Review",
    "Movies",
    "Books (Fiction)",
    "Books (Non-Fiction)",
    "TV-Series",
    "Manga",
    "Shower Thoughts",
    "Uncategorized"
];